# Generated by Django 3.2.14 on 2022-09-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hikes', '0005_scheduledhike_unique_hike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike_date', models.DateField()),
                ('num_hikers', models.IntegerField(default=1)),
                ('price_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hike_bookings', to='hikes.hike')),
            ],
        ),
    ]
