# Generated by Django 3.2.14 on 2022-10-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_booking_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=1, max_length=32, null=True),
        ),
    ]
