# Generated by Django 3.2.14 on 2022-10-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=1, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
