# Generated by Django 3.2.14 on 2022-07-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hike',
            old_name='desc',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='hike',
            name='name',
        ),
        migrations.AddField(
            model_name='hike',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Moderate'), (2, 'Difficult')], default=0),
        ),
        migrations.AddField(
            model_name='hike',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hike',
            name='title',
            field=models.CharField(default='added_tile', max_length=60),
            preserve_default=False,
        ),
    ]
