# Generated by Django 3.2.14 on 2022-07-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0003_auto_20220730_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikes.hike')),
            ],
        ),
    ]
