# Generated by Django 3.2.14 on 2022-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0004_scheduledhike'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scheduledhike',
            constraint=models.UniqueConstraint(fields=('hike', 'date'), name='unique_hike'),
        ),
    ]
